import pandas as pd
import string
import spacy

class data:
    def __init__(self):
        # Declaring Global Variables for the class
        self.raw_data = ""
        self.df = pd.DataFrame()
        self.declare_data()
        self.data_convert()

    # This Dataset has been completely created by Jose Berlin (i.e., the author) of this program
    def declare_data(self):
        self.raw_data = {'I would like to talk about Msc AI': 'select course',
                         'I want to talk about Bsc computer science': 'select course',
                         'I want to talk about Bsc psychology': 'select course',
                         'I would like to talk about MPhys Physics': 'select course',
                         'Tell me about Msc Actuarial Management with Data Science': 'select course',
                         'Tell me about Msc Applied Petroleum Geoscience': 'select course',
                         'I want to talk about MPhys Physics': 'select course',
                         'How about Msc': 'select course',
                         'How about Bsc': 'select course',
                         'How about MEng': 'select course',
                         'How about Beng': 'select course',
                         'Bachelors': 'select course',
                         'Masters': 'select course',
                         'post graduate': 'select course',
                         'postgraduate': 'select course',

                         'How are the courses delivered?': 'delivery',
                         'Is this a hybrid course?': 'delivery',
                         'what is the course delivery for this course?': 'delivery',
                         'Can I take the courses remotely?': 'delivery',
                         'What is the mode of course delivery for international students?': 'delivery',
                         'Do you offer part-time in this courses?': 'delivery',
                         'Is the courses self-paced?': 'delivery',
                         'Can i take this course online?': 'delivery',
                         'How is the course delivered?': 'delivery',
                         'How will i learn this course': 'delivery',

                         'Where are the courses conducted?': 'location',
                         'where is the course location?': 'location',
                         'Is this course conducted in edinburgh?': 'location',
                         'what are the course locations?': 'location',
                         'Do you have courses at multiple campuses?': 'location',
                         'what are the different course locations?': 'location',
                         'Which campus offers this locations?': 'location',
                         'Is this course conducted in dubai?': 'location',
                         'Can you provide the course locations?': 'location',
                         'Is this course conducted online?': 'location',
                         'where will I learn this course?': 'location',
                         'where can I do this program?': 'location',

                         'How long is the duration of this course?': 'duration',
                         'What is the typical duration of this program?': 'duration',
                         'Can you tell me about the duration of the course?': 'duration',
                         'How many months is this course?': 'duration',
                         'What is the duration of this program?': 'duration',
                         'How long does the course takes?': 'duration',
                         'Can you provide the duration for the course?': 'duration',
                         'How many years is the program?': 'duration',
                         'How long does it take for completing the course?': 'duration',
                         'Can you explain the duration of this program?': 'duration',

                         'Can you give me an overview of this course?': 'overview',
                         'Can you provide me an overview for this course?': 'overview',
                         'What is the main focus of this course?': 'overview',
                         'Tell me about this program': 'overview',
                         'What is the overview of this course?': 'overview',
                         'Provide an overview of the program': 'overview',
                         'What can I expect to learn in this course?': 'overview',
                         'Explain the main themes of this program': 'overview',
                         'Give me a brief overview of the program': 'overview',
                         'Tell me about this course?': 'overview',
                         'Tell me more about the program': 'overview',

                         'What are the specific subjects covered in this course?': 'course content',
                         'Can you list the modules included in this program?': 'course content',
                         'Provide details about the course content for the program': 'course content',
                         'What topics are included in this course?': 'course content',
                         'Explain the different units covered in this program': 'course content',
                         'Can you tell me about the curriculum of the course?': 'course content',
                         'What subjects will I study in the program?': 'course content',
                         'Give me an idea of the course content for this course': 'course content',
                         'What are the main units covered in this program?': 'course content',
                         'List the core courses included in this degree': 'course content',
                         'What is the outcomes of this program': 'course content',
                         'What are the outcomes of this course': 'course content',
                         'What will I learn in this course': 'course content',
                         'What are my learning from this course': 'course content',

                         'What are the entry requirements for this program?': 'entry requirements',
                         'Can you explain the eligibility criteria for this course?': 'entry requirements',
                         'What qualifications are needed for this degree?': 'entry requirements',
                         'Are there any specific entry requirements for international students?': 'entry requirements',
                         'What are the prerequisites for the program?': 'entry requirements',
                         'Can you provide information about the entry requirements for the course?': 'entry requirements',
                         'Explain the academic background required for this program': 'entry requirements',
                         'What qualifications are needed to enroll in the course?': 'entry requirements',
                         'Are there any language proficiency requirements for international students?': 'entry requirements',
                         'admission prerequisites': 'entry requirements',

                         'Can you tell about the program cost?': 'fees',
                         'Provide details about the financial aspects for this degree': 'fees',
                         'can you tell about the degree cost?': 'fees',
                         'Can you give me an idea of the tuition expenses?': 'fees',
                         'How much is the tuition fee for this course?': 'fees',
                         'Can you provide information about the fees for the program?': 'fees',
                         'Can you give me an estimate of the total fees for this degree?': 'fees',
                         'What is the cost of the program?': 'fees',
                         'Are there any additional fees for international students?': 'fees',
                         'Provide details about the financial aspects of this program': 'fees',
                         'Explain the tuition fee structure for this courses': 'fees',
                         'What are the fees for this program?': 'fees',
                         'I want to know the cost': 'fees',
                         'I want to know the price': 'fees',
                         'How about the price': 'fees',
                         'How about the cost': 'fees',
                         'fees structure': 'fees',
                         'tuition costs': 'fees',
                         'tuition fees': 'fees',
                         'Can you give me an estimate of the total fees for the degree?': 'fees',
                         'What is the fee breakdown for this courses?': 'fees',
                         'Provide details about the financial aspects of this degree': 'fees',
                         'Provide details about the financial aspects for this program': 'fees',

                         'How do I apply for this program?': 'apply',
                         'What is the application process for this course?': 'apply',
                         'Could you guide me on how to apply?': 'apply',
                         'What are the steps to enroll in this program?': 'apply',
                         'How can I submit my application for this course?': 'apply',
                         'What is the procedure for applying to this degree?': 'apply',
                         'Can you explain the how to apply?': 'apply',
                         'How to apply for this program?': 'apply',
                         'How can I start the application process?': 'apply',
                         'Where do I go to apply for this course?': 'apply',
                         'How should i move further': 'apply',
                         'What is the application procedure': 'apply',
                         'application process': 'apply',

                         'How can I get in touch with the program coordinators?': 'contact',
                         'Is there a way to contact the staff members of this course?': 'contact',
                         'Can you provide me with the contact details of the program faculty?': 'contact',
                         'Where can I find information to reach out to the course administrators?': 'contact',
                         'How do I communicate with the program advisors?': 'contact',
                         'What is the best way to contact the staff in charge of this degree?': 'contact',
                         'Could you give me the email addresses of the program staff?': 'contact',
                         'What are the contact options for reaching out to the course organizers?': 'contact',
                         'How can I connect with the faculty members of this program?': 'contact',
                         'How to contact faculty members': 'contact',
                         'Can you guide me on how to contact the program department?': 'contact',
                         'Whom can i talk to about this course': 'contact',
                         'whom can i talk to about it': 'contact',
                         'faculty contact details': 'contact',
                         'I want to talk with a person about it': 'contact',
                         'I want to talk with officials': 'contact',

                         'Course delivery': 'delivery',
                         'course location': 'location',
                         'course duration': 'duration',
                         'course overview': 'overview',
                         'course contents': 'course content',
                         'entry requirements': 'entry requirements',
                         'course fees': 'fees',
                         'apply': 'apply',
                         'apply for course': 'apply',
                         'contact': 'contact'}

    # Converting the raw data(i.e., dict) to the standardized format(i.e., Dataframe)
    def data_convert(self):
        self.df = pd.DataFrame(self.raw_data.items(), columns=["sentence", "intent"])

    def get_data(self):
        return self.df
